language: node_js

node_js:
  - "0.11"

before_install:
  - npm install -g grunt-cli testem

before_script:
  - testem launchers

script:
  - testem ci -l PhantomJS -d
  - cat testem.log

branches:
  only:
    - master
